# 计算机眼里的图像

In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

In [2]:
img = cv2.imread('333.jpg')
print(img.size)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
def cv_show(name,img):
    cv2.imshow(name,img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


944136


In [3]:
print(img)
img=cv2.imread('333.jpg',cv2.IMREAD_GRAYSCALE)
print(img)
cv_show('image',img)
cv2.imwrite('test1.png',img)
print(img.size)

[[[ 48  42   1]
  [ 48  42   1]
  [ 48  42   1]
  ...
  [  6  15   5]
  [  5  14   4]
  [  5  14   4]]

 [[ 48  42   1]
  [ 49  43   2]
  [ 49  43   2]
  ...
  [  8  17   7]
  [  7  16   6]
  [  7  16   6]]

 [[ 48  42   1]
  [ 49  43   2]
  [ 49  43   2]
  ...
  [  6  15   5]
  [  6  15   5]
  [  6  15   5]]

 ...

 [[118  85   0]
  [119  86   0]
  [119  86   0]
  ...
  [ 15  24   3]
  [ 15  24   3]
  [ 15  24   3]]

 [[117  83   0]
  [117  83   0]
  [117  83   0]
  ...
  [ 14  26   4]
  [ 13  25   3]
  [ 13  25   3]]

 [[115  84   0]
  [115  84   0]
  [115  84   0]
  ...
  [ 14  26   4]
  [ 14  26   4]
  [ 13  25   3]]]
[[30 30 30 ... 11 10 10]
 [30 31 31 ... 13 12 12]
 [30 31 31 ... 11 11 11]
 ...
 [63 64 64 ... 17 17 17]
 [62 62 62 ... 18 17 17]
 [62 62 62 ... 18 18 17]]
314712


In [4]:
vc=cv2.VideoCapture('123.mp4')

In [5]:
if vc.isOpened():
    open,frame=vc.read()#read()此函数返回2个：booler，numpy.ndarray(即读取视频的一帧的内容)
    print(type(frame))
else:
    open = False

<class 'numpy.ndarray'>


In [6]:
while open:
    ret,frame =vc.read()
    if frame is None:
        break
    if ret == True:
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)#cv2.COLOR_BGR2GRAY将图像通道转为灰度
        #cvtColor(对象，方法)对对象进行的行为结果返回
        cv2.imshow('result',gray)
        if cv2.waitKey(100)&0xff ==27:#cv2.waitKey() 0xff==27指的是退出键
            break
vc.release()
cv2.destroyAllWindows()

#### cv2.COLOR_BGR2GRAY 方法：将图像通道转为灰度
#### cv2.cvtColor(对象，方法)对对象进行的行为结果返回
#### cv2.waitKey()

# 截取部分图像

In [7]:
img=cv2.imread('333.jpg')
cat=img[0:200,0:200]
cv_show('cat',cat)

# 颜色通道的提取

In [8]:
b,g,r=cv2.split(img)

In [9]:
g

array([[42, 42, 42, ..., 15, 14, 14],
       [42, 43, 43, ..., 17, 16, 16],
       [42, 43, 43, ..., 15, 15, 15],
       ...,
       [85, 86, 86, ..., 24, 24, 24],
       [83, 83, 83, ..., 26, 25, 25],
       [84, 84, 84, ..., 26, 26, 25]], dtype=uint8)

In [10]:
g.shape

(558, 564)

In [11]:
img=cv2.merge((b,g,r))
img.shape

(558, 564, 3)

In [12]:
cv_show('ppp',img)

In [13]:
# 保留单独的色彩
cur_img= img.copy()
# print(cur_img[:])
# cur_img[:,:,:] = 0
# cur_img[:,:,:] = 0
# cv_show('c',cur_img[:5,:5,:])
print(cur_img[:5,:3,:])

[[[48 42  1]
  [48 42  1]
  [48 42  1]]

 [[48 42  1]
  [49 43  2]
  [49 43  2]]

 [[48 42  1]
  [49 43  2]
  [49 43  2]]

 [[47 41  0]
  [48 42  1]
  [48 42  1]]

 [[47 41  0]
  [48 42  1]
  [48 42  1]]]


### 图片格式为（行，列，rgb）

# 边界填充

In [14]:
top_size,bottom_size,left_size,right_size=(50,50,50,50)

In [15]:
wrap=cv2.copyMakeBorder(img,top_size,bottom_size,left_size,right_size,cv2.BORDER_REFLECT_101)
plt.imshow(wrap)

# 数值计算

## 直接对图像进行加10，是对所有的元素进行加10

In [16]:
img_1=cv2.imread('333.jpg')
img_2=cv2.imread('444.png')
img_12=img_1+10
img_1[:5,:,0]

array([[48, 48, 48, ...,  6,  5,  5],
       [48, 49, 49, ...,  8,  7,  7],
       [48, 49, 49, ...,  6,  6,  6],
       [47, 48, 48, ...,  4,  4,  4],
       [47, 48, 48, ...,  6,  6,  6]], dtype=uint8)

In [17]:
img_12[:5,:,0]

array([[58, 58, 58, ..., 16, 15, 15],
       [58, 59, 59, ..., 18, 17, 17],
       [58, 59, 59, ..., 16, 16, 16],
       [57, 58, 58, ..., 14, 14, 14],
       [57, 58, 58, ..., 16, 16, 16]], dtype=uint8)

## 要是直接用“+” 若数值溢出则使用溢出数值-256

In [18]:
(img_1+img_12+img_1+img_1)[:5,:,0]

array([[202, 202, 202, ...,  34,  30,  30],
       [202, 206, 206, ...,  42,  38,  38],
       [202, 206, 206, ...,  34,  34,  34],
       [198, 202, 202, ...,  26,  26,  26],
       [198, 202, 202, ...,  34,  34,  34]], dtype=uint8)

## cv2.add()这个函数溢出值直接为255

In [19]:
cv2.add(img_1,img_12)[:5,:,0]

array([[106, 106, 106, ...,  22,  20,  20],
       [106, 108, 108, ...,  26,  24,  24],
       [106, 108, 108, ...,  22,  22,  22],
       [104, 106, 106, ...,  18,  18,  18],
       [104, 106, 106, ...,  22,  22,  22]], dtype=uint8)

# 图像融合

In [20]:
# img_1+img_2

In [21]:
img_1.shape

(558, 564, 3)

In [22]:
img_2.shape

(558, 565, 3)

## cv2.resize(图片,(列，行))这个与shape方法所表示的位子是有出入的    这个函数是进行拉伸的行为
## 还可以用cv2.resize(img,(0,0),fx=1,fy=3) 对x，y方向进行拉伸

In [23]:
img_2=cv2.resize(img_2,(645,424))
img_2.shape
# cv_show('1',img_2)

(424, 645, 3)

In [24]:
res = cv2.resize(img,(0,0),fx=1,fy=3)
cv_show('',res)

## res = a*img_1+b*img_2+c

In [25]:
# res =cv2.addWeighted(img_1,0.4,img_2,0.6,0)
# cv_show('',res)
# # plt.imshow(res)

# 图像阈值

ret,dst=cv2.threshold(src,thresh,maxval,type)
- src:输入图为单通道
- 有许多的type

In [26]:
img_gray=cv2.imread('333gray.png')
ret,thresh1=cv2.threshold(img_gray,127,255,cv2.THRESH_TOZERO)
cv_show('',thresh1)

# 图像平滑（滤波）

In [27]:
# 均值滤波
# 简单的平均卷积操作
blur = cv2.blur(img,(3,3))

cv_show('',blur)

In [28]:
#方框滤波
# 基本和均值一样，可以选择归一化，否则容易越界
box = cv2.boxFilter(img,-1,(3,3),normalize=False)

cv_show('',box)

In [29]:
# 高斯滤波
aussian = cv2.GaussianBlur(img,(5,5),1)

cv_show('',aussian)

In [30]:
# 中值滤波
median = cv2.medianBlur(img,5)

cv_show('',median)

In [31]:
# 展示所有
res = np.hstack((blur,aussian,median))
cv_show('',res)

# 形态学——腐蚀操作

In [70]:
# 读取图像
img = cv2.imread('lys1.jpg',cv2.IMREAD_GRAYSCALE)

# 利用图像阈值操作实现颜色的反转
ret,thresh1=cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)

cv_show('',thresh1)

In [71]:
# 创建一个核
kernel = np.ones((3,3),np.uint8)

# 使用腐蚀函数 `cv2.erode` 迭代次数为：1
erosion = cv2.erode(thresh1, kernel, iterations = 1)

# 展示效果
cv_show('',erosion)

# 形态学-膨胀操作

In [72]:
# 创建一个核用于膨胀操作
kernel = np.ones((3,3),np.uint8)

#开始膨胀操作 `cv2.dilate` 迭代次数为：1
dilate = cv2.dilate(img,kernel,iterations=1)

#展示
cv_show('',dilate)

# 开运算和闭运算

In [73]:
# 开运算：先腐蚀再膨胀
# 创建一个核(5,5)
kernel = np.ones((5,5), np.uint8)

# 进行开运算
opening = cv2.morphologyEx(thresh1, cv2.MORPH_OPEN, kernel)

#展示
cv_show('',opening)

In [74]:
# 闭运算：先膨胀再腐蚀

# 进行闭运算
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

#展示
cv_show('',closing)

# 梯度运算

In [75]:
# 梯度=膨胀-腐蚀
# 创建一个核(7,7)
img = cv2.imread('lys1.jpg')
kernel = np.ones((7,7), np.uint8)
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

#展示
cv_show('',gradient)

# 礼帽和黑帽
- 礼帽 = 原始输入 - 开运算结果 ————实际就等于开运算剔除掉的内容
- 黑帽 = 闭运算 - 原始输入 ——————

In [77]:
# 礼帽
tophat = cv2.morphologyEx(thresh1, cv2.MORPH_OPEN, kernel)

#展示
cv_show('',tophat)

In [78]:
#黑帽
blackhat = cv2.morphologyEx(thresh1, cv2.MORPH_BLACKHAT, kernel)

#展示
cv_show('',blackhat)